version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    
    groups:
      astro:
        patterns:
          - "@astrojs/*"
          - "astro"
          - "astro-*"
      
      development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
